# Generated by Django 2.0.7 on 2020-04-28 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='place',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.AlterField(
            model_name='area',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
