# Generated by Django 2.0.7 on 2020-04-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20200428_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['user']},
        ),
    ]
